## kubectl get deploy
## kubectl scale deploy <deployment_name> --replicas=5
## kubectl set image deploy <deployment_name> <container_name=image_name>
## kubectl rollout status deploy <deployment_name>
## kubectl rollout undo deploy <deployment_name> --to-revision=1
## kubectl rollout history deploy <deployment_name>
## kubectl annotate deployment/<deplyment_name> kubernetes.io/change-cause="rollback to previous versions"

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      name: swiggy-pod
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: shaikmustafa/mygame
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: swiggysvcnp
spec:
  type: NodePort
  selector:
    app: swiggy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008