## kubectl get cm
## kubectl describe cm <cm_name>
## kubectl create cm cm2 --from-literal="Name=Rammohan" --from-literal="Course=Java" --from-literal="Place=OWK"  ---> imparative way to create cm
## create .env file with nam app.env with key=values >> eg: app=dev  place=hyd
## kubectl create cm <cm_name> --from-env-file=app.env  ---> imparative way

#####
##1 we can attach a complete cm to a pod
##2 we can attach multiple cm
##3 we can attach a spec values from a cm to pod
##3 we can attach a diff values from diff cm to a pod

---
## example 1 & 2
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cm1
data:
  PORT: "3306"
  DB_NAME: "mysql"
  COURSE: "DevOps"
  CLOUD: "AWS"

---
apiVersion: v1 
kind: Pod 
metadata:
  name: ex-pod
spec:
  containers:
    - name: cont-1
      image: shaikmustafa/dm 
      ports: 
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: cm1
        - configMapRef:
            name: cm2   


---
apiVersion: v1 
kind: Pod 
metadata:
  name: ex-pod-1
spec:
  containers:
    - name: cont-1
      image: shaikmustafa/dm 
      ports: 
        - containerPort: 80
      env: 
        - name: mycloud
          valueFrom:
            configMapKeyRef:
              key: CLOUD 
              name: cm1 
        - name: myportsql
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: cm1 
        - name: mycource
          valueFrom: 
            configMapKeyRef:
              name: cm2
              key: Course 